### ISSUE TITLE
All the correct answers are the first option?

### ISSUE THREAD

**Issue by xmflswood** [RawEvan/OQuiz#2]
![image](https://cloud.githubusercontent.com/assets/13427833/24842605/c38273d2-1dcc-11e7-8168-22d662d7c1ae.png)
I think you'd better to add random answer in this game.

**Comment by RawEvan** [comment]
Fix in commits 00783fabd31bdb22ce7a4ec633d1ef5590dac4d1 and ec31b6c0cc98ae28ee48e988a675b9a90b502bba , release v0.0.5 https://github.com/RawEvan/OQuiz/releases/tag/v0.0.5
Thanks and enjoy it.
